Added support for multiple alternative messages/callsigns
lora-aprs/LoRa_APRS_Tracker pull request #47
Opened 2021-12-04 03:16 UTC by tekk

As per #45 
- moved `button_tx` to separate `button` config subitem and added `alt_message` option (both set to true by default)
- added support for multiple callsigns / messages / icons / overlays (switch by holding the middle button)
- made `beacons` JSON config to be an array (you can add as much beacon configs as you want)

2021-12-04 05:45 UTC, peterus commented
@tekk I like the idea and will definitely merge it. I will take some more time to analyze the changes as I think there are some small improvements.

2021-12-06 10:14 UTC, tekk commented
That's awesome @peterus thanks for letting me know.
If there is anything that I can fix straight away, please let me know and I will do my best to improve the code.
I also see that the `pio check` and formatting checks are failing. (I don't know why?)
Obviously I tested the functionality before making a PR and also guys from our local club are testing my branch on their T-Beams.
If there is anything that I could help with, please let me know.

2021-12-06 21:03 UTC, peterus requested changes
Hi @tekk!
I found some improvements which should be fixed.
If you have questions, please get in contact with me again.
Don't care about the failing style-checker, I will fix it when you are finished.

2021-12-06 21:03 UTC, peterus commented on src/LoRa_APRS_Tracker.cpp
> +    Configuration::Beacon beacon = Config.GetCurrentBeacon();
Do not get the current beacon config all the time when the message should be sent. The beacon config will not change so often, instead use the `handle_next_beacon` function to store a pointer to the config.

2021-12-06 21:03 UTC, peterus commented on src/LoRa_APRS_Tracker.cpp
> +  Configuration::Beacon beacon = Config.SetNextBeacon();
store the beacon config local in the module and use it in the different functions.

2021-12-14 23:04 UTC, peterus commented
@tekk do you need some help to fix all the requested changes? :)

2021-12-15 07:01 UTC, tekk commented
@peterus Yes I indeed need help. I started to rewrite the code, but I'm not that much familiar with C++. Could you please help fixing the issues?

2021-12-15 08:54 UTC, tekk commented
@peterus It would be best if you could do the fixes as it's years ago when I last worked with C++. I'm not familiar with smart pointers either. May I please ask you to fix my code? Apart from that, I'm also very busy with my daily job. Please help me fix this branch so we could all profit 😄 Apologies for the dirty code.

2021-12-15 15:28 UTC, tekk commented
I was thinking of something like this to manage the current Beacon:

```
class BeaconManager {
  public:
    BeaconManager(Config &config) {};
    std::list<Config::Beacon>::iterator currentBeacon;
    const Configuration::Beacon* const nextBeacon() const;

  private:
    const Configuration::Config* const config;
}
```

But I'm not entirely sure how to implement it.
@peterus Please help!

2021-12-19 22:44 UTC, merged

2021-12-19 22:45 UTC, peterus commented
thanks @tekk for the initial idea!